crud/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.inicio, name='inicio'),
    path('nosotros/', views.nosotros, name='nosotros'),

    # aquí se solo las rutas de los productos

    path('productos/', views.productos, name='productos'),
    path('productos/crear', views.crear, name='crear'),
    path('productos/editar', views.editar, name='editar'),
    path('productos/eliminar/<int:id>', views.eliminar, name='eliminar'),
    path('productos/editar/<int:id>/', views.editar, name='editar'),

    # aquí se solo las rutas de los proveedores

    path('proveedores/', views.proveedores, name='proveedores'),
    path('proveedores/crear', views.crear_proveedor, name='crear_proveedor'),
    path('proveedores/editar', views.editar_proveedor, name='editar_proveedor'),
    path('proveedores/eliminar/<int:id>', views.eliminar_proveedor, name='eliminar_proveedor'),
    path('proveedores/editar/<int:id>/', views.editar_proveedor, name='editar_proveedor'),

    # aquí se solo las rutas de los suministros

    path('suministros/', views.suministros, name='suministros'),
    path('suministros/crear', views.crear_suministro, name='crear_suministro'),
    path('suministros/editar', views.editar_suministro, name='editar_suministro'),
    path('suministros/eliminar/<int:id>', views.eliminar_suministro, name='eliminar_suministro'),
    path('suministros/editar/<int:id>/', views.editar_suministro, name='editar_suministro'),


]

sistema/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('crud.urls')),
]

crud/models.py
from django.db import models

# Create your models here.

class Producto(models.Model):
    id = models.AutoField(primary_key=True)
    nombre = models.CharField(max_length=50, verbose_name="Nombre")
    descripcion = models.TextField(verbose_name="Descripción", blank=True, null=True)
    stock = models.IntegerField(default=0)  # Siempre inicia en 0
    estado = models.IntegerField(choices=[(1, "Activo"), (0, "Inactivo")], default=1)

    class Meta:
        db_table = "productos"  # Aquí defines el nombre correcto

    def __str__(self):
        superior = "Producto: " + self.nombre
        return superior


class Proveedor(models.Model):
    id = models.AutoField(primary_key=True)
    nombre = models.CharField(max_length=100, verbose_name="Nombre")
    estado = models.IntegerField(
        choices=[(1, "Activo"), (0, "Inactivo")], 
        default=1  # Siempre inicia en 1 (activo)
    )

    class Meta:
        db_table = "proveedores" 

    def __str__(self):
        superior = "Proveedor: " + self.nombre
        return superior


class Suministro(models.Model):
    producto = models.ForeignKey('Producto', on_delete=models.CASCADE)
    proveedor = models.ForeignKey('Proveedor', on_delete=models.CASCADE)
    cantidad = models.IntegerField()
    fecha_creacion = models.DateTimeField(auto_now_add=True)  

    def save(self, *args, **kwargs):
        # Obtener el suministro previo si existe
        if self.pk:
            suministro_anterior = Suministro.objects.get(pk=self.pk)
            diferencia = self.cantidad - suministro_anterior.cantidad  # Ajustar diferencia en stock
            self.producto.stock += diferencia
        else:
            # Si es un nuevo suministro, simplemente sumarlo
            self.producto.stock += self.cantidad

        self.producto.save()  # Guardar cambios en el producto
        super().save(*args, **kwargs)

    class Meta:
        db_table = "suministros"

   

crud/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from .models import Producto, Proveedor, Suministro
from .form import ProductoForm, ProductoFormeditar, ProveedorForm, ProveedorFormeditar, SuministroForm, SuministroFormeditar

# Create your views here.

def inicio(request):
    # Renderiza la página de inicio
    return render(request, 'paginas/inicio.html')

def nosotros(request):
    # Renderiza la página de información sobre la empresa
    return render(request, 'paginas/nosotros.html')

# Aquí se crean las funciones para manejar los productos

def productos(request):
    # Obtiene todos los productos de la base de datos
    productos = Producto.objects.all()
    return render(request, 'productos/indexp.html', {'productos': productos})

def crear(request):
    # Procesa el formulario para crear un nuevo producto
    formulario = ProductoForm(request.POST or None, request.FILES or None)
    if formulario.is_valid():  # Si el formulario es válido, guarda el producto
        formulario.save()
        return redirect('productos')  # Redirige a la lista de productos
    return render(request, 'productos/crear.html', {'formulario': formulario})

def editar(request, id):
    # Obtiene el producto a editar por su ID
    producto = Producto.objects.get(id=id)
    formulario = ProductoFormeditar(request.POST or None, request.FILES or None, instance=producto)
    if formulario.is_valid() and request.POST:  # Si el formulario es válido, guarda los cambios
        formulario.save()
        return redirect('productos')  # Redirige a la lista de productos
    return render(request, 'productos/editar.html', {'formulario': formulario})

def eliminar(request, id):
    # Obtiene el producto por su ID y lo elimina
    producto = Producto.objects.get(id=id)
    producto.delete()
    return redirect('productos')  # Redirige a la lista de productos


# aqui se crean las funciones para los proveedores

def proveedores(request):
    proveedores = Proveedor.objects.all()
    return render(request, 'proveedores/indexpr.html', {'proveedores': proveedores})

def crear_proveedor(request):
    formulario = ProveedorForm(request.POST or None, request.FILES or None)
    if formulario.is_valid():
        formulario.save()
        return redirect('proveedores')
    return render(request, 'proveedores/crear.html', {'formulario': formulario})

def editar_proveedor(request, id):
    proveedor = Proveedor.objects.get(id=id)
    formulario = ProveedorFormeditar(request.POST or None, request.FILES or None, instance=proveedor)
    if formulario.is_valid() and request.POST:
        formulario.save()
        return redirect('proveedores')
    return render(request, 'proveedores/editar.html', {'formulario': formulario})

def eliminar_proveedor(request, id):
    proveedor = Proveedor.objects.get(id=id)
    proveedor.delete()
    return redirect('proveedores')

# aqui se crean las funciones de suministros

def suministros(request):
    suministros = Suministro.objects.all()
    return render(request, 'suministros/indexs.html', {'suministros': suministros})

def crear_suministro(request):
    formulario = SuministroForm(request.POST or None, request.FILES or None)
    if formulario.is_valid():
        formulario.save()
        return redirect('proveedores')
    return render(request, 'proveedores/crear.html', {'formulario': formulario})

def editar_suministro(request, id):
    suministro = Suministro.objects.get(id=id)
    formulario = SuministroFormeditar(request.POST or None, request.FILES or None, instance=suministro)
    if formulario.is_valid() and request.POST:
        formulario.save()
        return redirect('suministros')
    return render(request, 'suministros/editar.html', {'formulario': formulario})

def eliminar_suministro(request, id):
    suministro = Suministro.objects.get(id=id)
    suministro.delete()
    return redirect('suministros')

crud/templates/base.html
{% load static %}
<!doctype html>
<html lang="en">

<head>
    <title>{% block titulo %} {% endblock %}</title>
    <!-- Required meta tags -->
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />

    <!-- Bootstrap CSS v5.2.1 -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous" />
</head>

<body>

    <nav class="navbar navbar-expand navbar-light bg-light">
        <div class="nav navbar-nav">
            <a class="nav-item nav-link" href="{% url 'inicio' %}">inicio</a>
            <a class="nav-item nav-link" href="{% url 'nosotros' %}">nosotros</a>
            <a class="nav-item nav-link" href="{% url 'productos' %}">productos</a>
            <a class="nav-item nav-link" href="{% url 'proveedores' %}">proveedores</a>
            <a class="nav-item nav-link" href="{% url 'suministros' %}">suministros</a>
        </div>
    </nav>


    <div class="container">
        <div class="row">
            <div class="col-12">
                <br>
                {% block contenido %} {% endblock %} 
            </div>
        </div>
    </div>

    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js"
        integrity="sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r"
        crossorigin="anonymous"></script>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.min.js"
        integrity="sha384-BBtl+eGJRgqQAUMxJ7pMwbEyER4l1g+O15P+16Ep7Q9Q+zqX6gSbd85u4mG4QzX+"
        crossorigin="anonymous"></script>
</body>

</html>

crud/templates/paginas/inicio.html
{% extends "base.html" %}

{% block titulo %} Inicio {% endblock %}

{% block contenido %}







<div class="p-5 mb-4 bg-light rounded-3 bg-primary  text-center py-5">
    <div class="container-fluid py-5">
       
        <h1 class="display-5 fw-bold">Bienvenidos al sitio de gestion de suministros</h1>
        <br><br>
        <p class=" fs-4">
            Este es un sitio web de inventario, donde podras agregar, editar y eliminar productos, proveedores y suministros.</p>
            <hr>
            <br>
        <a href="{% url 'nosotros' %}"><button class="btn btn-primary btn-lg" type="button"">
            Empezar
        </button></a>
    </div>
</div>

<footer class="bg-dark text-white text-center py-3">
    <p>&copy; 2025 Mi Sitio. Todos los derechos reservados.</p>
</footer>


{% endblock %} 

crud/templates/paginas/nosotros.html
{% extends "base.html" %}

{% block titulo %} nosotros {% endblock %}

{% block contenido %}

seccion nosotros 

{% endblock %} 

crud/templates/productos/crear.html
{% extends "base.html" %}

{% block titulo %} Agregar Producto {% endblock %}

{% block contenido %}

<div class="card">
    <div class="card-header">crear producto</div>
    <div class="card-body">
        <h4 class="card-title">datos del producto</h4>
        {% include 'productos/form.html' %}
    </div>
    
</div>


{% endblock %} 

crud/templates/productos/editar.html
{% extends "base.html" %}

{% block titulo %} Editar producto {% endblock %}

{% block contenido %}
<div class="card">
    <div class="card-header">editar producto</div>
    <div class="card-body">
        <h4 class="card-title">datos del producto</h4>
        {% include 'productos/form.html' %}
    </div>
     
</div>

{% endblock %} 

crud/templates/productos/form.html
<form enctype="multipart/form-data" method="post">

    {% csrf_token %}
    {% for campo in formulario %}
        <div class="mb-3">
            <label for="" class="form-label">{{ campo.label }}:</label>
            <input type="{{ campo.field.widget.input_type }}" 
            class="form-control"
            name="{{ campo.name }}" 
            id=""
            aria-describedby="helpId"
            placeholder="{{ campo.label }}"
            value="{{ campo.value | default:'' }}" />
        </div>
        
    {% endfor %}
    <input
        name=""
        id=""
        class="btn btn-success"
        type="submit"
        value="enviar informacion"
    />
    <a
        name=""
        id=""
        class="btn btn-primary"
        href="{% url 'productos' %}"
        role="button"
        >CANCELAR</a
    >
    
    
</form>

crud/templates/productos/indexp.html
{% extends "base.html" %}

{% block titulo %} Productos {% endblock %}

{% block contenido %}

<div class="card">
    <div class="card-header">
        <a name="" id="" class="btn btn-success" href="{% url 'crear' %}" role="button">Agregar nuevo producto</a>

    </div>
    <div class="card-body">
        <h4 class="card-title">Productos</h4>

        <div class="table-responsive">
            <table class="table table-secundary table-bordered table-hover">
                <thead>
                    <tr>
                        <th scope="col">ID</th>
                        <th scope="col">Nombre</th>
                        <th scope="col">Descripcion </th>
                        <th scope="col">Stock</th>
                        <th scope="col">Estado</th>
                        <th scope="col">Acciones</th>

                    </tr>
                </thead>
                <tbody>
                    {% for producto in productos %}
                    <tr class="">
                        <td scope="row">{{ producto.id }}</td>
                        <td>{{ producto.nombre }}</td>
                        <td>{{ producto.descripcion }}</td>
                        <td>{{ producto.stock }}</td>
                        <td>{{ producto.get_estado_display }}</td>
                        <td><a name="" id="" class="btn btn-info" href="{% url 'editar' producto.id %}" role="button">Editar</a> |
                            <a name="" id="" class="btn btn-danger" href="{% url 'eliminar' producto.id %}" role="button"
                            onclick="return confirm('¿Estás seguro de que deseas eliminar este producto?');">Borrar</a>
                           </td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>


    </div>
    <div class="card-footer text-muted"></div>
</div>


{% endblock %}

crud/templates/proveedores/crear.html
{% extends "base.html" %}

{% block titulo %} Agregar Proveedor {% endblock %}

{% block contenido %}

<div class="card">
    <div class="card-header">crear Proveedor</div>
    <div class="card-body">
        <h4 class="card-title">datos del Proveedor</h4>
        {% include 'proveedores/form.html' %}
    </div>
    
</div>


{% endblock %} 

crud/templates/proveedores/editar.html
{% extends "base.html" %}

{% block titulo %} Editar proveedor {% endblock %}

{% block contenido %}
<div class="card">
    <div class="card-header">editar proveedor</div>
    <div class="card-body">
        <h4 class="card-title">datos del proveedor</h4>
        {% include 'proveedores/form.html' %}
    </div>
     
</div>

{% endblock %} 

crud/templates/proveedores/form.html
<form enctype="multipart/form-data" method="post">

    {% csrf_token %}
    {% for campo in formulario %}
        <div class="mb-3">
            <label for="" class="form-label">{{ campo.label }}:</label>
            <input type="{{ campo.field.widget.input_type }}" 
            class="form-control"
            name="{{ campo.name }}" 
            id=""
            aria-describedby="helpId"
            placeholder="{{ campo.label }}"
            value="{{ campo.value | default:'' }}" />
        </div>
        
    {% endfor %}
    <input
        name=""
        id=""
        class="btn btn-success"
        type="submit"
        value="enviar informacion"
    />
    <a
        name=""
        id=""
        class="btn btn-primary"
        href="{% url 'proveedores' %}"
        role="button"
        >CANCELAR</a
    >
    
    
</form>

crud/templates/proveedores/indexpr.html
{% extends "base.html" %}

{% block titulo %} proveedores {% endblock %}

{% block contenido %}

<div class="card">
    <div class="card-header">
        <a name="" id="" class="btn btn-success" href="{% url 'crear_proveedor' %}" role="button">Agregar nuevo
            proveedor</a>

    </div>
    <div class="card-body">
        <h4 class="card-title">Proveedores</h4>

        <div class="table-responsive">
            <table class="table table-secundary table-bordered table-hover">
                <thead>
                    <tr>
                        <th scope="col">ID</th>
                        <th scope="col">Nombre</th>
                        <th scope="col">Estado</th>
                        <th scope="col">Acciones</th>

                    </tr>
                </thead>
                <tbody>
                    {% for proveedor in proveedores %}
                    <tr class="">
                        <td scope="row">{{ proveedor.id }}</td>
                        <td>{{ proveedor.nombre }}</td>
                        <td>{{ proveedor.get_estado_display }}</td>
                        <td><a name="" id="" class="btn btn-info" href="{% url 'editar_proveedor' proveedor.id %}" role="button">Editar</a> ㅤ | ㅤ
                            <a name="" id="" class="btn btn-danger" href="{% url 'eliminar_proveedor' proveedor.id %}" role="button"
                                onclick="return confirm('¿Estás seguro de que deseas eliminar este proveedor?');"> Borrar
                            </a>

                        </td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>


    </div>
    <div class="card-footer text-muted"></div>
</div>
{% endblock %}

crud/templates/suministros/crear.html
{% extends "base.html" %}

{% block titulo %} Agregar Sumunistro {% endblock %}

{% block contenido %}

<div class="card">
    <div class="card-header">crear Sumunistro</div>
    <div class="card-body">
        <h4 class="card-title">datos del Sumunistro</h4>
        {% include 'sumunistros/form.html' %}
    </div>
    
</div>


{% endblock %} 

crud/templates/suministros/editar.html
{% extends "base.html" %}

{% block titulo %} Editar proveedor {% endblock %}

{% block contenido %}
<div class="card">
    <div class="card-header">editar suministro</div>
    <div class="card-body">
        <h4 class="card-title">datos del suministro</h4>
        {% include 'suministros/form.html' %}
    </div>
     
</div>

{% endblock %} 

crud/templates/suministros/form.html
<form enctype="multipart/form-data" method="post">

    {% csrf_token %}
    {% for campo in formulario %}
        <div class="mb-3">
            <label for="" class="form-label">{{ campo.label }}:</label>
            <input type="{{ campo.field.widget.input_type }}" 
            class="form-control"
            name="{{ campo.name }}" 
            id=""
            aria-describedby="helpId"
            placeholder="{{ campo.label }}"
            value="{{ campo.value | default:'' }}" />
        </div>
        
    {% endfor %}
    <input
        name=""
        id=""
        class="btn btn-success"
        type="submit"
        value="enviar informacion"
    />
    <a
        name=""
        id=""
        class="btn btn-primary"
        href="{% url 'suministros' %}"
        role="button"
        >CANCELAR</a
    >
    
    
</form>

crud/templates/suministros/indexs.html
{% extends "base.html" %}

{% block titulo %} proveedores {% endblock %}

{% block contenido %}

<div class="card">
    <div class="card-header">
        <a name="" id="" class="btn btn-success" href="{% url 'crear_suministro' %}" role="button">Agregar nuevo suministro</a>

    </div>
    <div class="card-body">
        <h4 class="card-title">Suministros</h4>

        <div class="table-responsive">
            <table class="table table-secundary table-bordered table-hover">
                <thead>
                    <tr>
                        <th scope="col">ID | NOMBRE PRODUCTO</th>
                        <th scope="col">ID | NOMBRE PROVEEDOR</th>
                        <th scope="col">Cantidad</th>
                        <th scope="col">Fechas Creación</th>
                        <th scope="col">Acciones</th>

                    </tr>
                </thead>
                <tbody>
                    {% for suministro in suministros %}
                    <tr class="">
                        <td scope="row">{{ suministro.producto.id }} | {{ suministro.producto.nombre }} </td>
                        <td scope="row">{{ suministro.proveedor.id }} | {{ suministro.proveedor.nombre }}</td>
                        <td>{{ suministro.cantidad }}</td>
                        <td>{{ suministro.fecha_creacion }}</td>
                        <td>
                            <a class="btn btn-info" href="{% url 'editar_suministro' suministro.id %}" role="button">Editar</a>
                            <a class="btn btn-danger" href="{% url 'eliminar_suministro' suministro.id %}" role="button"
                               onclick="return confirm('¿Estás seguro de que deseas eliminar este suministro?');">
                               Borrar
                            </a>
                        </td>                        
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>


    </div>
    <div class="card-footer text-muted"></div>
</div>
{% endblock %}